/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;

import java.awt.event.ActionEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author User
 */
public class BookingFrame extends javax.swing.JFrame {

    /**
     * Creates new form BookingFrameHua
     *
     *
     *
     */
    FoodInit runFoodInit = new FoodInit();
    DefaultComboBoxModel currentMenuCombox = new DefaultComboBoxModel();
    DefaultListModel<String> currentCustomerFoodList = new DefaultListModel<>();
    Food customersSelection;

    //Change the value of chosenMenu to whatever comes from the previous booking step
    FoodMenu chosenMenu = runFoodInit.economyClassMenu;

    private Ticket ticket;

    private Customer newCustomer = new Customer();
    private Section typeChosen;

    private Flight customerPlane = new Flight();

    List<Flight> flightList = new ArrayList<>();

    Locale swedish = new Locale("swe", "se");
    private final NumberFormat nf = NumberFormat.getCurrencyInstance(swedish);
    private double income = 0d;
    private JRadioButton[] flightRadioButton;

    public BookingFrame(List<Flight> flightList) {
        runFoodInit.runInit();

        initCustomComponents();

        initComponents();

        jComboBox1.setSelectedIndex(0);

        this.flightList = flightList;
        flightRadioButton = new JRadioButton[flightList.size()];

        for (int i = 0; i < flightList.size(); i++) {
            flightRadioButton[i] = new JRadioButton();
            flightRadioButton[i].setText(flightList.get(i).getPlaneID());
            flightRadioButton[i].setFont(chooseFlightLabel.getFont());
            flightRadioButtonPanel.add(flightRadioButton[i]);

            buttonGroup1.add(flightRadioButton[i]);

        }
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        subStartPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        bookPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        infoLabel = new javax.swing.JLabel();
        containPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        subRegisterPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        iDLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        iDTextField = new javax.swing.JTextField();
        cancelButtonRegisterPanel = new javax.swing.JButton();
        nextButtonRegisterPanel = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        planePanel = new javax.swing.JPanel();
        subPlanePanel = new javax.swing.JPanel();
        flightRadioButtonPanel = new javax.swing.JPanel();
        chooseFlightLabel = new javax.swing.JLabel();
        classRadioButtonPanel = new javax.swing.JPanel();
        chooseClassLabel = new javax.swing.JLabel();
        firstClassButton = new javax.swing.JRadioButton();
        economyClassButton = new javax.swing.JRadioButton();
        actionButtonPlanePanel = new javax.swing.JPanel();
        nextButtonPlanePanel = new javax.swing.JButton();
        cancelButtonPlanePanel = new javax.swing.JButton();
        previousButtonPlanePanel = new javax.swing.JButton();
        foodContainPanel = new javax.swing.JPanel();
        foodPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        removeItemFromListButton = new javax.swing.JButton();
        clearListButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        orderListItemPriceLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        orderListTotalPriceLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        menuAmountPanel = new javax.swing.JPanel();
        plusButton = new java.awt.Button();
        minusButton = new java.awt.Button();
        amountToBuy = new javax.swing.JLabel();
        menuItemPricePanel = new javax.swing.JPanel();
        menuItemPriceLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addToCartButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        reviewPanel = new javax.swing.JPanel();
        subReviewPanel = new javax.swing.JPanel();
        reviewLabel = new javax.swing.JLabel();
        cancelButtonReviewPanel = new javax.swing.JButton();
        previousButtonReviewPanel = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        reviewScrollPane = new javax.swing.JScrollPane();
        reviewTextArea = new javax.swing.JTextArea();
        mainMenuBar = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        testMenu = new javax.swing.JMenu();
        addTicketsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        startPanel.setPreferredSize(new java.awt.Dimension(978, 474));
        startPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subStartPanel.setPreferredSize(new java.awt.Dimension(958, 474));

        startButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLabel.setText("Welcome to SAABAIR");

        javax.swing.GroupLayout subStartPanelLayout = new javax.swing.GroupLayout(subStartPanel);
        subStartPanel.setLayout(subStartPanelLayout);
        subStartPanelLayout.setHorizontalGroup(
            subStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subStartPanelLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(subStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(welcomeLabel)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        subStartPanelLayout.setVerticalGroup(
            subStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subStartPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        startPanel.add(subStartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 950, 450));

        mainPanel.add(startPanel, "card3");

        bookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight information"));
        infoScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        infoScrollPane.setHorizontalScrollBar(null);
        infoScrollPane.setVerifyInputWhenFocusTarget(false);
        infoScrollPane.setWheelScrollingEnabled(false);

        infoTextArea.setEditable(false);
        infoTextArea.setColumns(20);
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        infoScrollPane.setViewportView(infoTextArea);

        infoPanel.add(infoScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 310, 370));

        infoLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        infoLabel.setText("Welcome to SAAB");
        infoPanel.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        bookPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 470));

        containPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        containPanel.setLayout(new java.awt.CardLayout());

        registerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registerPanel.setPreferredSize(new java.awt.Dimension(620, 450));

        subRegisterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Register"));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Name:");

        iDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iDLabel.setText("ID Number:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        cancelButtonRegisterPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtonRegisterPanel.setText("Cancel");
        cancelButtonRegisterPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonRegisterPanelActionPerformed(evt);
            }
        });

        nextButtonRegisterPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextButtonRegisterPanel.setText("Next");
        nextButtonRegisterPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonRegisterPanelActionPerformed(evt);
            }
        });

        registerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLabel.setText("Please register:");

        javax.swing.GroupLayout subRegisterPanelLayout = new javax.swing.GroupLayout(subRegisterPanel);
        subRegisterPanel.setLayout(subRegisterPanelLayout);
        subRegisterPanelLayout.setHorizontalGroup(
            subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subRegisterPanelLayout.createSequentialGroup()
                        .addComponent(cancelButtonRegisterPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButtonRegisterPanel))
                    .addGroup(subRegisterPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(iDLabel)
                            .addComponent(registerLabel))
                        .addGap(18, 18, 18)
                        .addGroup(subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                            .addComponent(iDTextField))))
                .addContainerGap())
        );
        subRegisterPanelLayout.setVerticalGroup(
            subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subRegisterPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(registerLabel)
                .addGap(18, 18, 18)
                .addGroup(subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDLabel)
                    .addComponent(iDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(subRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtonRegisterPanel)
                    .addComponent(nextButtonRegisterPanel))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        containPanel.add(registerPanel, "card2");

        planePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        planePanel.setPreferredSize(new java.awt.Dimension(620, 450));

        subPlanePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight and Class"));
        subPlanePanel.setLayout(new java.awt.BorderLayout());

        flightRadioButtonPanel.setLayout(new java.awt.GridLayout(0, 1));

        chooseFlightLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chooseFlightLabel.setText("Please choose flight:");
        flightRadioButtonPanel.add(chooseFlightLabel);

        subPlanePanel.add(flightRadioButtonPanel, java.awt.BorderLayout.WEST);

        classRadioButtonPanel.setLayout(new java.awt.GridLayout(0, 1));

        chooseClassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chooseClassLabel.setText("Please choose class:");
        classRadioButtonPanel.add(chooseClassLabel);

        buttonGroup2.add(firstClassButton);
        firstClassButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstClassButton.setText("First Class");
        firstClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassButtonActionPerformed(evt);
            }
        });
        classRadioButtonPanel.add(firstClassButton);

        buttonGroup2.add(economyClassButton);
        economyClassButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        economyClassButton.setText("Economy Class");
        economyClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyClassButtonActionPerformed(evt);
            }
        });
        classRadioButtonPanel.add(economyClassButton);

        subPlanePanel.add(classRadioButtonPanel, java.awt.BorderLayout.EAST);

        actionButtonPlanePanel.setMaximumSize(new java.awt.Dimension(500, 500));
        actionButtonPlanePanel.setMinimumSize(new java.awt.Dimension(400, 406));
        actionButtonPlanePanel.setPreferredSize(new java.awt.Dimension(460, 80));
        actionButtonPlanePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextButtonPlanePanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextButtonPlanePanel.setText("Next");
        nextButtonPlanePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonPlanePanelActionPerformed(evt);
            }
        });
        actionButtonPlanePanel.add(nextButtonPlanePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        cancelButtonPlanePanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtonPlanePanel.setText("Cancel");
        cancelButtonPlanePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonPlanePanelActionPerformed(evt);
            }
        });
        actionButtonPlanePanel.add(cancelButtonPlanePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        previousButtonPlanePanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButtonPlanePanel.setText("Previous");
        previousButtonPlanePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonPlanePanelActionPerformed(evt);
            }
        });
        actionButtonPlanePanel.add(previousButtonPlanePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        subPlanePanel.add(actionButtonPlanePanel, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout planePanelLayout = new javax.swing.GroupLayout(planePanel);
        planePanel.setLayout(planePanelLayout);
        planePanelLayout.setHorizontalGroup(
            planePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPlanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
        );
        planePanelLayout.setVerticalGroup(
            planePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPlanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containPanel.add(planePanel, "card2");

        foodContainPanel.setPreferredSize(new java.awt.Dimension(620, 450));
        foodContainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        foodPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(currentCustomerFoodList);
        jList1.setToolTipText("Select food from the drop down and press the add button.");
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        foodPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 170, 344));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your order");
        foodPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 170, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeItemFromListButton.setText("Remove");
        removeItemFromListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeItemFromListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemFromListButtonActionPerformed(evt);
            }
        });
        jPanel8.add(removeItemFromListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 90, 50));

        clearListButton.setText("Clear list");
        clearListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearListButtonActionPerformed(evt);
            }
        });
        jPanel8.add(clearListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, 40));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Item price"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderListItemPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderListItemPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(orderListItemPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 56, 56));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        foodPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 36, 100, 401));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Total price"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderListTotalPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderListTotalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice()));
        jPanel10.add(orderListTotalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 150, 18));

        foodPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 385, 170, 55));

        foodContainPanel.add(foodPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 292, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setMaximumRowCount(16);
        jComboBox1.setModel(currentMenuCombox);
        jComboBox1.setToolTipText("Select food from the drop down and press the add button.");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 298, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 298, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getName()));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getDescription());
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 25, 170, 260));

        menuAmountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Amount"));
        menuAmountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        plusButton.setLabel(">");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        menuAmountPanel.add(plusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 25, 8, 40));

        minusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        minusButton.setLabel("<");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        menuAmountPanel.add(minusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 25, 8, 40));

        amountToBuy.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        amountToBuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountToBuy.setText("1");
        menuAmountPanel.add(amountToBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 45));

        jPanel3.add(menuAmountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, 80, 80));

        menuItemPricePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Price"));
        menuItemPricePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuItemPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuItemPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuItemPriceLabel.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getPrice().toString());
        menuItemPricePanel.add(menuItemPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, 40));

        jPanel3.add(menuItemPricePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 80, 76));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 298, 308));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addToCartButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addToCartButton.setText("Add to cart");
        addToCartButton.setMaximumSize(new java.awt.Dimension(120, 30));
        addToCartButton.setMinimumSize(new java.awt.Dimension(120, 30));
        addToCartButton.setPreferredSize(new java.awt.Dimension(120, 30));
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });
        jPanel7.add(addToCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 115, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Next");
        jButton7.setMaximumSize(new java.awt.Dimension(75, 31));
        jButton7.setMinimumSize(new java.awt.Dimension(75, 31));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 0, 84, 50));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Previous");
        jButton12.setMaximumSize(new java.awt.Dimension(75, 31));
        jButton12.setMinimumSize(new java.awt.Dimension(75, 31));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 84, 50));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 388, 290, -1));

        foodContainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 0, 320, 470));

        containPanel.add(foodContainPanel, "card6");

        reviewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reviewPanel.setPreferredSize(new java.awt.Dimension(620, 450));

        subReviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Review"));

        reviewLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reviewLabel.setText("Please review your journey:");

        cancelButtonReviewPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtonReviewPanel.setText("Cancel");
        cancelButtonReviewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonReviewPanelActionPerformed(evt);
            }
        });

        previousButtonReviewPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButtonReviewPanel.setText("Previous");
        previousButtonReviewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonReviewPanelActionPerformed(evt);
            }
        });

        payButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        payButton.setText("Confirm and Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        reviewTextArea.setEditable(false);
        reviewTextArea.setColumns(20);
        reviewTextArea.setLineWrap(true);
        reviewTextArea.setRows(5);
        reviewTextArea.setWrapStyleWord(true);
        reviewScrollPane.setViewportView(reviewTextArea);

        javax.swing.GroupLayout subReviewPanelLayout = new javax.swing.GroupLayout(subReviewPanel);
        subReviewPanel.setLayout(subReviewPanelLayout);
        subReviewPanelLayout.setHorizontalGroup(
            subReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subReviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subReviewPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cancelButtonReviewPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previousButtonReviewPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payButton)
                        .addGap(8, 8, 8))
                    .addComponent(reviewScrollPane)
                    .addGroup(subReviewPanelLayout.createSequentialGroup()
                        .addComponent(reviewLabel)
                        .addContainerGap(393, Short.MAX_VALUE))))
        );
        subReviewPanelLayout.setVerticalGroup(
            subReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subReviewPanelLayout.createSequentialGroup()
                .addComponent(reviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButtonReviewPanel)
                    .addComponent(payButton)
                    .addComponent(cancelButtonReviewPanel))
                .addContainerGap())
        );

        javax.swing.GroupLayout reviewPanelLayout = new javax.swing.GroupLayout(reviewPanel);
        reviewPanel.setLayout(reviewPanelLayout);
        reviewPanelLayout.setHorizontalGroup(
            reviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subReviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        reviewPanelLayout.setVerticalGroup(
            reviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subReviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        containPanel.add(reviewPanel, "card2");

        bookPanel.add(containPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 0, 624, 474));

        mainPanel.add(bookPanel, "card2");

        getContentPane().add(mainPanel, java.awt.BorderLayout.PAGE_START);

        mainMenu.setText("BookingSystem");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(exitMenuItem);

        mainMenuBar.add(mainMenu);

        testMenu.setText("ForTest");

        addTicketsMenuItem.setText("Book tickets");
        addTicketsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketsMenuItemActionPerformed(evt);
            }
        });
        testMenu.add(addTicketsMenuItem);

        mainMenuBar.add(testMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void nextButtonRegisterPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonRegisterPanelActionPerformed
        String name;
        String iD;

        name = nameTextField.getText();
        iD = iDTextField.getText();

        if (name.equals("") || iD.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Name and ID number can't be empty!");
        } else {

            newCustomer.setName(name);
            newCustomer.setiD(iD);

            registerPanel.setVisible(false);
            planePanel.setVisible(true);
            foodContainPanel.setVisible(false);
            reviewPanel.setVisible(false);

            if (flightList.stream().filter(s -> !s.isFlight()).collect(Collectors.toList()).isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "All planes have left, please wait!");
            }

        }

    }//GEN-LAST:event_nextButtonRegisterPanelActionPerformed


    private void cancelButtonRegisterPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonRegisterPanelActionPerformed
        startPanel.setVisible(true);
        bookPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonRegisterPanelActionPerformed

    private void previousButtonReviewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonReviewPanelActionPerformed
        registerPanel.setVisible(false);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(true);
        reviewPanel.setVisible(false);
    }//GEN-LAST:event_previousButtonReviewPanelActionPerformed

    private void firstClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstClassButtonActionPerformed
        typeChosen = Section.First;
    }//GEN-LAST:event_firstClassButtonActionPerformed

    private void economyClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyClassButtonActionPerformed
        typeChosen = Section.Economy;
    }//GEN-LAST:event_economyClassButtonActionPerformed

    private void nextButtonPlanePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonPlanePanelActionPerformed

        if (customerPlane.getPlaneID() == null) {
            JOptionPane.showMessageDialog(this, "Please choose plane!");
        } else if (typeChosen == null) {
            JOptionPane.showMessageDialog(rootPane, "Please choose Class!");
        } else if (customerPlane.isFlight()) {
            JOptionPane.showMessageDialog(rootPane, "Flight " + customerPlane + " has left, please choose another one!");
        } else {
            try {
                ticket = customerPlane.getTicketList().searchAvailableTicket(typeChosen);
                int count = chosenMenu.getListSize();
                switch (typeChosen) {
                    case Economy:
                        if (chosenMenu != runFoodInit.economyClassMenu) {
                            chosenMenu = runFoodInit.economyClassMenu;
                            currentCustomerFoodList.removeAllElements();
                            newCustomer.clearMyFoodList();
                            orderListTotalPriceLabel.setText("");
                        }

                        break;
                    case First:
                        if (chosenMenu != runFoodInit.firstClassMenu) {
                            chosenMenu = runFoodInit.firstClassMenu;
                            currentCustomerFoodList.removeAllElements();
                            newCustomer.clearMyFoodList();
                            orderListTotalPriceLabel.setText("");
                        }

                        break;

                }

                for (Food next : chosenMenu.getList()) {
                    currentMenuCombox.insertElementAt(next.getName(), chosenMenu.getList().indexOf(next));
                    jComboBox1.setSelectedIndex(0);
                }

                for (int i = (chosenMenu.getListSize() + count); i > chosenMenu.getListSize(); i--) {

                    currentMenuCombox.removeElementAt(i - 1);

                }

                registerPanel.setVisible(false);
                planePanel.setVisible(false);
                foodContainPanel.setVisible(true);
                reviewPanel.setVisible(false);
            } catch (SeatNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No available seat in " + typeChosen + " Class, please choose another section!");
            }
            

        }


    }//GEN-LAST:event_nextButtonPlanePanelActionPerformed

    private void previousButtonPlanePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonPlanePanelActionPerformed
        registerPanel.setVisible(true);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(false);
    }//GEN-LAST:event_previousButtonPlanePanelActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed

        
        if (ticket.getCustomer() == null) {
            currentCustomerFoodList.removeAllElements();
            orderListTotalPriceLabel.setText("");
            ticket.setCustomer(newCustomer);
            System.out.println(customerPlane.getPlaneID() + ": " + "1 ticket is sold\n");
            System.out.println(customerPlane.getPlaneID() + ": " + customerPlane.getTotalNoAvailableSeat() + " ticket left\n");
            customerPlane.setIsFlight();

            startPanel.setVisible(true);
            bookPanel.setVisible(false);

            System.out.print("Currently total income is: ");
            income += ticket.getTotalPrice();
            System.out.println(nf.format(income));
            System.out.println("Currently total profit is: " + nf.format(income * 0.3));
        } else {
            JOptionPane.showMessageDialog(this, "The seat assigned is not available, please select plane and class again!");
        }


    }//GEN-LAST:event_payButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        newCustomer = new Customer();
        nameTextField.setText("");
        iDTextField.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        customerPlane = new Flight();
        typeChosen = null;

        for (int i = 0; i < flightList.size(); i++) {
            //add allow listener
            JRadioButton currentRadioButton = flightRadioButton[i];
            flightRadioButton[i].addActionListener((ActionEvent e) -> {
                customerPlane = flightList.get(Arrays.asList(flightRadioButton).indexOf(currentRadioButton));
                double ticketPrice = 0d;
                for (Ticket next : customerPlane.getTicketList().getList()) {
                    if (next.getSection() == Section.First) {
                        ticketPrice = next.getPrice();
                    }
                }
                firstClassButton.setText("First Class: " + nf.format(ticketPrice));
                for (Ticket next : customerPlane.getTicketList().getList()) {
                    if (next.getSection() == Section.Economy) {
                        ticketPrice = next.getPrice();
                    }
                }
                economyClassButton.setText("Economy Class: " + nf.format(ticketPrice));

            });
        }

        startPanel.setVisible(false);

        bookPanel.setVisible(true);
        registerPanel.setVisible(true);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(false);


    }//GEN-LAST:event_startButtonActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        String selectedMenuItem = jList1.getSelectedValue();

        if (selectedMenuItem != null) {
            orderListItemPriceLabel.setText(Double.toString(chosenMenu.findFoodByName(selectedMenuItem).getPrice()));
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void removeItemFromListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemFromListButtonActionPerformed

        String selectedMenuItem = jList1.getSelectedValue();
        if (selectedMenuItem != null) {
            newCustomer.removeFromMyFoodList(chosenMenu.findFoodByName(selectedMenuItem));
            currentCustomerFoodList.removeAllElements();
            for (int i = 0; i < newCustomer.getMyFoodList().size(); i++) {
                currentCustomerFoodList.addElement(newCustomer.getMyFoodList().get(i).getName());
            }
            orderListItemPriceLabel.setText("");
            
            //orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice())); //by Hua
            orderListTotalPriceLabel.setText(nf.format(newCustomer.getFoodPrice()));
        }

    }//GEN-LAST:event_removeItemFromListButtonActionPerformed

    private void clearListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearListButtonActionPerformed

        newCustomer.clearMyFoodList();
        currentCustomerFoodList.removeAllElements();
        //orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice())); //by Hua
        orderListTotalPriceLabel.setText(nf.format(newCustomer.getFoodPrice()));

    }//GEN-LAST:event_clearListButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed

        int buyAmount = Integer.parseInt(amountToBuy.getText());
        buyAmount++;
        amountToBuy.setText(Integer.toString(buyAmount));
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        JFrame frame = new JFrame();
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        int buyAmount = Integer.parseInt(amountToBuy.getText());
        switch (buyAmount) {
            case 1:
                JOptionPane.showMessageDialog(frame, "Can not order less than one item");
                break;
            default:
                buyAmount--;
                amountToBuy.setText(Integer.toString(buyAmount));
                break;
        }
    }//GEN-LAST:event_minusButtonActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed

        currentCustomerFoodList.removeAllElements();
        int buyAmount = Integer.parseInt(amountToBuy.getText());

        for (int i = 0; i < buyAmount; i++) {
            if (customersSelection != null) {
                newCustomer.addToMyFoodList(customersSelection);
            }

        }
        for (int i = 0; i < newCustomer.getMyFoodList().size(); i++) {
            currentCustomerFoodList.addElement(newCustomer.getMyFoodList().get(i).getName());
            //System.out.println(newCustomer.getMyFoodList().get(i).toString());
        }
        //orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice()));  //by Hua
        orderListTotalPriceLabel.setText(nf.format(newCustomer.getFoodPrice()));
        
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        registerPanel.setVisible(false);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(true);

        reviewTextArea.setText("");
        reviewTextArea.append("Name: " + newCustomer.getName() + "\n");
        reviewTextArea.append("ID Number: " + newCustomer.getiD() + "\n");
        reviewTextArea.append("Fight: " + customerPlane.getPlaneID() + "\n");
        reviewTextArea.append("Seat number: " + ticket.getSection() + " Class " + ticket.getSeatNumber() + "\n");
        reviewTextArea.append("Price: " + nf.format(ticket.getPrice())+ "\n");
        reviewTextArea.append("Reserved food : \n");
        newCustomer.getMyFoodList().forEach(s -> reviewTextArea.append("       " + s.getName() + " " + nf.format(s.getPrice()) + "\n"));
        reviewTextArea.append("Total food price: " + nf.format(newCustomer.getFoodPrice()) + "\n");
        reviewTextArea.append("-------------\n");
        reviewTextArea.append("Total: " + nf.format(ticket.getTotalPrice() + newCustomer.getFoodPrice()) + "\n");


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        registerPanel.setVisible(false);
        planePanel.setVisible(true);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void addTicketsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketsMenuItemActionPerformed
        // TODO add your handling code here:

        Flight flightTest;
        String selectFlight = JOptionPane.showInputDialog(this, "Type in the plane iD: ");
        int inputNumberTickets;
        for (Flight next : flightList) {
            if (next.getPlaneID().equalsIgnoreCase(selectFlight)) {
                flightTest = next;
                int ticketLeft = flightTest.getTotalNoAvailableSeat();
                String inputString = JOptionPane.showInputDialog(this, "input number of tickets you want to buy, maximum " + (ticketLeft - 1));
                if (inputString != null) {
                    inputNumberTickets = Integer.parseInt(inputString);
                    Customer customerTest = new Customer();
                    if (inputNumberTickets < ticketLeft) {
                        int i = inputNumberTickets;

                        for (Ticket nextTicket : flightTest.getTicketList().getList()) {
                            if (nextTicket.getCustomer() == null && i != 0) {
                                customerTest.setName("CustomerTest00" + i);
                                customerTest.setiD("12" + i + "234" + i);
                                nextTicket.setCustomer(customerTest);
                                income += nextTicket.getTotalPrice();
                                i--;
                            }
                        }

                        System.out.println(flightTest.getPlaneID() + ": " + inputNumberTickets + " tickets are sold\n");
                        System.out.println(flightTest.getPlaneID() + ": " + flightTest.getTotalNoAvailableSeat() + " ticket left\n");
                    }
                }

            }

        }


    }//GEN-LAST:event_addTicketsMenuItemActionPerformed

    private void cancelButtonReviewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonReviewPanelActionPerformed
        startPanel.setVisible(true);
        bookPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonReviewPanelActionPerformed

    private void cancelButtonPlanePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPlanePanelActionPerformed
        startPanel.setVisible(true);
        bookPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonPlanePanelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        String selectedMenuItem = (String) currentMenuCombox.getSelectedItem();
        if (selectedMenuItem != null) {

            customersSelection = chosenMenu.findFoodByName(selectedMenuItem);
            jTextArea3.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getDescription());
            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(currentMenuCombox.getSelectedItem().toString()));
            menuItemPriceLabel.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getPrice().toString());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void initCustomComponents() {
        //currentMenuCombox.removeAllElements();
        //Collections.sort(chosenMenu.getList());
        for (int i = 0; i < chosenMenu.getListSize(); i++) {

            currentMenuCombox.addElement(chosenMenu.getFoodAtIndex(i).getName());

        }
    }

    public int convertUserInputToInt(String userInput) {

        if (userInput == null || userInput.isEmpty()) {
            userInput = "1";
        }
        StringBuilder sb = new StringBuilder();
        boolean found = false;
        for (char c : userInput.toCharArray()) {
            if (Character.isDigit(c)) {
                sb.append(c);
                found = true;
            } else if (found) {
                // If we already found a digit before and this char is not a digit, stop looping
                break;
            }
        }
        userInput = sb.toString();
        if (sb.toString().isEmpty() || sb.toString() == null) {
            userInput = "1";
        }

        int buyAmount = Integer.parseInt(userInput);
        if (buyAmount <= 0) {
            buyAmount = 1;
        }
        return buyAmount;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        List<Flight> flightList = new ArrayList<>();

        Flight saab0001 = new Saab();
        saab0001.setPlaneID("SAAB0001");
        flightList.add(saab0001);
        Flight saab0002 = new Saab();
        saab0002.setPlaneID("SAAB0002");
        flightList.add(saab0002);
        Flight saab0003 = new Saab();
        saab0003.setPlaneID("SAAB0003");
        flightList.add(saab0003);

        //Flight saab0004 = new Saab();
        //saab0004.setPlaneID("SAAB0004");
        //flightList.add(saab0004);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BookingFrame bk = new BookingFrame(flightList);
                bk.setVisible(true);

                for(Flight next: flightList) {
                    new Thread(new FlightInformation(next, bk.infoTextArea)).start();
                    
                }
                
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonPlanePanel;
    private javax.swing.JMenuItem addTicketsMenuItem;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JLabel amountToBuy;
    private javax.swing.JPanel bookPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelButtonPlanePanel;
    private javax.swing.JButton cancelButtonRegisterPanel;
    private javax.swing.JButton cancelButtonReviewPanel;
    private javax.swing.JLabel chooseClassLabel;
    private javax.swing.JLabel chooseFlightLabel;
    private javax.swing.JPanel classRadioButtonPanel;
    private javax.swing.JButton clearListButton;
    private javax.swing.JPanel containPanel;
    private javax.swing.JRadioButton economyClassButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JRadioButton firstClassButton;
    private javax.swing.JPanel flightRadioButtonPanel;
    private javax.swing.JPanel foodContainPanel;
    private javax.swing.JPanel foodPanel1;
    private javax.swing.JLabel iDLabel;
    private javax.swing.JTextField iDTextField;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuAmountPanel;
    public javax.swing.JLabel menuItemPriceLabel;
    private javax.swing.JPanel menuItemPricePanel;
    private java.awt.Button minusButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton nextButtonPlanePanel;
    private javax.swing.JButton nextButtonRegisterPanel;
    public javax.swing.JLabel orderListItemPriceLabel;
    public javax.swing.JLabel orderListTotalPriceLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JPanel planePanel;
    private java.awt.Button plusButton;
    private javax.swing.JButton previousButtonPlanePanel;
    private javax.swing.JButton previousButtonReviewPanel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton removeItemFromListButton;
    private javax.swing.JLabel reviewLabel;
    private javax.swing.JPanel reviewPanel;
    private javax.swing.JScrollPane reviewScrollPane;
    private javax.swing.JTextArea reviewTextArea;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JPanel subPlanePanel;
    private javax.swing.JPanel subRegisterPanel;
    private javax.swing.JPanel subReviewPanel;
    private javax.swing.JPanel subStartPanel;
    private javax.swing.JMenu testMenu;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
