/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author User
 */
public class BookingFrame extends javax.swing.JFrame {

    /**
     * Creates new form BookingFrameHua
     *
     *
     *
     */
    FoodInit runFoodInit = new FoodInit();
    DefaultComboBoxModel currentMenuCombox = new DefaultComboBoxModel();
    DefaultListModel<String> currentCustomerFoodList = new DefaultListModel<>();
    Food customersSelection;

    //Change the value of chosenMenu to whatever comes from the previous booking step
    FoodMenu chosenMenu = runFoodInit.economyClassMenu;

    private Ticket ticket;

    private Customer newCustomer = new Customer();
    private SeatType typeChosen;

    private Flight customerPlane = new Flight();

    List<Flight> flightList = new ArrayList<>();

    private double income;
    private double profit;
    private JRadioButton[] flightRadioButton;
    private int icount=0;

    public BookingFrame(List<Flight> flightList) {
        runFoodInit.runInit();
        
        initCustomComponents();
        
        
        initComponents();
        
        jComboBox1.setSelectedIndex(0);
        
        this.flightList = flightList;
        flightRadioButton = new JRadioButton[flightList.size()];

        flightRadioButton[0] = new JRadioButton();
        flightRadioButton[1] = new JRadioButton();
        flightRadioButton[2] = new JRadioButton();

        for (int i = 0; i < flightList.size(); i++) {
            flightRadioButton[i] = new JRadioButton();
            flightRadioButton[i].setText(flightList.get(i).getPlaneID());
            flightRadioButton[i].setFont(jLabel4.getFont());
            radioButtonPanel.add(flightRadioButton[i]);

            buttonGroup1.add(flightRadioButton[i]);

        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel14 = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        subStartPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        bookPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        containPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        iDLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        iDTextField = new javax.swing.JTextField();
        cancelButtonRegisterPanel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        planePanel = new javax.swing.JPanel();
        subPlanePanel = new javax.swing.JPanel();
        radioButtonPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        firstClassButton = new javax.swing.JRadioButton();
        economyClassButton = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        cancelButtonPlanePanel = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        foodContainPanel = new javax.swing.JPanel();
        foodPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        removeItemFromListButton = new javax.swing.JButton();
        clearListButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        orderListItemPriceLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        orderListTotalPriceLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        menuAmountPanel = new javax.swing.JPanel();
        plusButton = new java.awt.Button();
        minusButton = new java.awt.Button();
        amountToBuy = new javax.swing.JLabel();
        menuItemPricePanel = new javax.swing.JPanel();
        menuItemPriceLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addToCartButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        reviewPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cancelButtonReviewPanel = new javax.swing.JButton();
        previousButtonReviewPanel = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel14.setLayout(new java.awt.CardLayout());

        startPanel.setPreferredSize(new java.awt.Dimension(978, 474));
        startPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subStartPanel.setPreferredSize(new java.awt.Dimension(958, 474));

        startButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLabel.setText("Welcome to SAAB");

        javax.swing.GroupLayout subStartPanelLayout = new javax.swing.GroupLayout(subStartPanel);
        subStartPanel.setLayout(subStartPanelLayout);
        subStartPanelLayout.setHorizontalGroup(
            subStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subStartPanelLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addGroup(subStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subStartPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subStartPanelLayout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(391, 391, 391))))
        );
        subStartPanelLayout.setVerticalGroup(
            subStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subStartPanelLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        startPanel.add(subStartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 950, 450));

        jPanel14.add(startPanel, "card3");

        bookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight information"));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        infoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 310, 370));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Welcome to SAAB");
        infoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        bookPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 470));

        containPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        containPanel.setLayout(new java.awt.CardLayout());

        registerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registerPanel.setPreferredSize(new java.awt.Dimension(620, 450));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Register"));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Name:");

        iDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iDLabel.setText("ID Number:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        cancelButtonRegisterPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtonRegisterPanel.setText("Cancel");
        cancelButtonRegisterPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonRegisterPanelActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Please register:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cancelButtonRegisterPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(iDLabel)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                            .addComponent(iDTextField))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDLabel)
                    .addComponent(iDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtonRegisterPanel)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        containPanel.add(registerPanel, "card2");

        planePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        planePanel.setPreferredSize(new java.awt.Dimension(620, 450));

        subPlanePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight and Class"));
        subPlanePanel.setLayout(new java.awt.BorderLayout());

        radioButtonPanel.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Please choose flight:");
        radioButtonPanel.add(jLabel4);

        subPlanePanel.add(radioButtonPanel, java.awt.BorderLayout.WEST);

        jPanel11.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Please choose class:");
        jPanel11.add(jLabel5);

        buttonGroup2.add(firstClassButton);
        firstClassButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstClassButton.setText("First Class");
        firstClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassButtonActionPerformed(evt);
            }
        });
        jPanel11.add(firstClassButton);

        buttonGroup2.add(economyClassButton);
        economyClassButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        economyClassButton.setText("Economy Class");
        economyClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyClassButtonActionPerformed(evt);
            }
        });
        jPanel11.add(economyClassButton);

        subPlanePanel.add(jPanel11, java.awt.BorderLayout.EAST);

        jPanel12.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel12.setMinimumSize(new java.awt.Dimension(400, 406));
        jPanel12.setPreferredSize(new java.awt.Dimension(460, 80));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Next");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        cancelButtonPlanePanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtonPlanePanel.setText("Cancel");
        cancelButtonPlanePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonPlanePanelActionPerformed(evt);
            }
        });
        jPanel12.add(cancelButtonPlanePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Previous");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        subPlanePanel.add(jPanel12, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout planePanelLayout = new javax.swing.GroupLayout(planePanel);
        planePanel.setLayout(planePanelLayout);
        planePanelLayout.setHorizontalGroup(
            planePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPlanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        planePanelLayout.setVerticalGroup(
            planePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPlanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containPanel.add(planePanel, "card2");

        foodContainPanel.setPreferredSize(new java.awt.Dimension(620, 450));
        foodContainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        foodPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(currentCustomerFoodList);
        jList1.setToolTipText("Select food from the drop down and press the add button.");
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        foodPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 170, 344));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your order");
        foodPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 170, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeItemFromListButton.setText("Remove");
        removeItemFromListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeItemFromListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemFromListButtonActionPerformed(evt);
            }
        });
        jPanel8.add(removeItemFromListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 90, 50));

        clearListButton.setText("Clear list");
        clearListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearListButtonActionPerformed(evt);
            }
        });
        jPanel8.add(clearListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, 40));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Item price"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderListItemPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderListItemPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(orderListItemPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 56, 56));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        foodPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 36, 100, 401));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Total price"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderListTotalPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderListTotalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice()));
        jPanel10.add(orderListTotalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 150, 18));

        foodPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 385, 170, 55));

        foodContainPanel.add(foodPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 292, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setMaximumRowCount(16);
        jComboBox1.setModel(currentMenuCombox);
        jComboBox1.setToolTipText("Select food from the drop down and press the add button.");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 298, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 298, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getName()));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getDescription());
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 25, 170, 260));

        menuAmountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Amount"));
        menuAmountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        plusButton.setLabel(">");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        menuAmountPanel.add(plusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 25, 8, 40));

        minusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        minusButton.setLabel("<");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        menuAmountPanel.add(minusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 25, 8, 40));

        amountToBuy.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        amountToBuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountToBuy.setText("1");
        menuAmountPanel.add(amountToBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 45));

        jPanel3.add(menuAmountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, 80, 80));

        menuItemPricePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Price"));
        menuItemPricePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuItemPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuItemPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuItemPriceLabel.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getPrice().toString());
        menuItemPricePanel.add(menuItemPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, 40));

        jPanel3.add(menuItemPricePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 80, 76));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 298, 308));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addToCartButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addToCartButton.setText("Add to cart");
        addToCartButton.setMaximumSize(new java.awt.Dimension(120, 30));
        addToCartButton.setMinimumSize(new java.awt.Dimension(120, 30));
        addToCartButton.setPreferredSize(new java.awt.Dimension(120, 30));
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });
        jPanel7.add(addToCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 115, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Next");
        jButton7.setMaximumSize(new java.awt.Dimension(75, 31));
        jButton7.setMinimumSize(new java.awt.Dimension(75, 31));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 0, 84, 50));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Previous");
        jButton12.setMaximumSize(new java.awt.Dimension(75, 31));
        jButton12.setMinimumSize(new java.awt.Dimension(75, 31));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 84, 50));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 388, 290, -1));

        foodContainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 0, 320, 470));

        containPanel.add(foodContainPanel, "card6");

        reviewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reviewPanel.setPreferredSize(new java.awt.Dimension(620, 450));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Review"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Please review your journey:");

        cancelButtonReviewPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtonReviewPanel.setText("Cancel");
        cancelButtonReviewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonReviewPanelActionPerformed(evt);
            }
        });

        previousButtonReviewPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButtonReviewPanel.setText("Previous");
        previousButtonReviewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonReviewPanelActionPerformed(evt);
            }
        });

        payButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        payButton.setText("Confirm and Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cancelButtonReviewPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previousButtonReviewPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payButton)
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(393, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButtonReviewPanel)
                    .addComponent(payButton)
                    .addComponent(cancelButtonReviewPanel))
                .addContainerGap())
        );

        javax.swing.GroupLayout reviewPanelLayout = new javax.swing.GroupLayout(reviewPanel);
        reviewPanel.setLayout(reviewPanelLayout);
        reviewPanelLayout.setHorizontalGroup(
            reviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        reviewPanelLayout.setVerticalGroup(
            reviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        containPanel.add(reviewPanel, "card2");

        bookPanel.add(containPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 0, 624, 474));

        jPanel14.add(bookPanel, "card2");

        getContentPane().add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("BookingSystem");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("ForTest");

        jMenuItem2.setText("Book tickets");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name;
        String iD;

        name = nameTextField.getText();
        iD = iDTextField.getText();

        if (name.equals("") || iD.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Name and person number can't be empty!");
        } else {

            newCustomer.setName(name);
            newCustomer.setiD(iD);

            registerPanel.setVisible(false);
            planePanel.setVisible(true);
            foodContainPanel.setVisible(false);
            reviewPanel.setVisible(false);

            if (flightList.stream().filter(s -> s.isFlight()).collect(Collectors.toList()).size() == flightList.size()) {
                JOptionPane.showMessageDialog(rootPane, "All planes have left, please wait!");
            }

        }

    }//GEN-LAST:event_jButton4ActionPerformed


    private void cancelButtonRegisterPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonRegisterPanelActionPerformed
        startPanel.setVisible(true);
        bookPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonRegisterPanelActionPerformed

    private void previousButtonReviewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonReviewPanelActionPerformed
        registerPanel.setVisible(false);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(true);
        reviewPanel.setVisible(false);
    }//GEN-LAST:event_previousButtonReviewPanelActionPerformed

    private void firstClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstClassButtonActionPerformed
        typeChosen = SeatType.FirstClass;
    }//GEN-LAST:event_firstClassButtonActionPerformed

    private void economyClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyClassButtonActionPerformed
        typeChosen = SeatType.EconomyClass;
    }//GEN-LAST:event_economyClassButtonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (customerPlane.getPlaneID() == null) {
            JOptionPane.showMessageDialog(this, "Please choose plane!");
        } else if (typeChosen == null) {
            JOptionPane.showMessageDialog(rootPane, "Please choose Class!");
        } else if (customerPlane.isFlight()) {
            JOptionPane.showMessageDialog(rootPane, "Plane you chosen has left, please choose another one!");
        } else {
            try {
                ticket = customerPlane.getTicketList().searchAvailableTicket(typeChosen);
                int count = chosenMenu.getListSize();
                switch (typeChosen) {
                    case EconomyClass:
                        if(chosenMenu!=runFoodInit.economyClassMenu){
                            chosenMenu = runFoodInit.economyClassMenu;
                            currentCustomerFoodList.removeAllElements();
                            newCustomer.clearMyFoodList();
                        }
                        
                        break;
                    case FirstClass:
                        if(chosenMenu!=runFoodInit.firstClassMenu){
                            chosenMenu = runFoodInit.firstClassMenu;
                            currentCustomerFoodList.removeAllElements();
                            newCustomer.clearMyFoodList();
                        }
                        
                        break;

                }
                
                for(Food next:chosenMenu.getList()) {
                   currentMenuCombox.insertElementAt(next.getName(), chosenMenu.getList().indexOf(next));
                   jComboBox1.setSelectedIndex(0);
                }
                
                for (int i = (chosenMenu.getListSize() + count); i > chosenMenu.getListSize(); i--) {
                 
                currentMenuCombox.removeElementAt(i-1);
                   
                }
                
                registerPanel.setVisible(false);
                planePanel.setVisible(false);
                foodContainPanel.setVisible(true);
                reviewPanel.setVisible(false);
            } catch (SeatNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No available seat in chosen class. please choose another section?");
            }

        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        registerPanel.setVisible(true);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed

        currentCustomerFoodList.removeAllElements();
        orderListTotalPriceLabel.setText("");
        ticket.setCustomer(newCustomer);
        jTextArea1.append(customerPlane.getPlaneID() + ": " + "1 ticket is sold\n");
        jTextArea1.append(customerPlane.getPlaneID() + ": " + customerPlane.getTotalNoAvailableSeat() + " ticket left\n");
        customerPlane.setIsFlight();

        startPanel.setVisible(true);
        bookPanel.setVisible(false);

        System.out.print("Currently total income is: ");
        income = 0d;
        flightList.forEach((next) -> {
            income += next.getIncome();
        });
        System.out.println(income + " SEK");
        System.out.println("Currently total profit is: " + income * 0.3 + " SEK");


    }//GEN-LAST:event_payButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        newCustomer = new Customer();
        nameTextField.setText("");
        iDTextField.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        customerPlane = new Flight();
        typeChosen = null;

        for (int i = 0; i < flightList.size(); i++) {
            //add allow listener
            JRadioButton currentRadioButton = flightRadioButton[i];
            flightRadioButton[i].addActionListener((ActionEvent e) -> {
                customerPlane = flightList.get(Arrays.asList(flightRadioButton).indexOf(currentRadioButton));
                double ticketPrice=0d;
                for(Ticket next:customerPlane.getTicketList().getList()){
                    if(next.getSeatType()==SeatType.FirstClass){
                        ticketPrice = next.getPrice();
                    }
                }
                firstClassButton.setText("First Class: " + ticketPrice + "SEK");
                for(Ticket next:customerPlane.getTicketList().getList()){
                    if(next.getSeatType()==SeatType.EconomyClass){
                        ticketPrice = next.getPrice();
                    }
                }
                economyClassButton.setText("Economy Class: " + ticketPrice + "SEK");
                
                
            });
        }

        startPanel.setVisible(false);

        bookPanel.setVisible(true);
        registerPanel.setVisible(true);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(false);


    }//GEN-LAST:event_startButtonActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        String selectedMenuItem = jList1.getSelectedValue();

        if (selectedMenuItem != null) {
            orderListItemPriceLabel.setText(Double.toString(chosenMenu.findFoodByName(selectedMenuItem).getPrice()));
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void removeItemFromListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemFromListButtonActionPerformed

        String selectedMenuItem = jList1.getSelectedValue();
        if (selectedMenuItem != null) {
            newCustomer.removeFromMyFoodList(chosenMenu.findFoodByName(selectedMenuItem));
            currentCustomerFoodList.removeAllElements();
            for (int i = 0; i < newCustomer.getMyFoodList().size(); i++) {
                currentCustomerFoodList.addElement(newCustomer.getMyFoodList().get(i).getName());
            }
            orderListItemPriceLabel.setText("");
            orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice()));
        }

    }//GEN-LAST:event_removeItemFromListButtonActionPerformed

    private void clearListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearListButtonActionPerformed

        newCustomer.clearMyFoodList();
        currentCustomerFoodList.removeAllElements();
        orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice()));

    }//GEN-LAST:event_clearListButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed

        int buyAmount = Integer.parseInt(amountToBuy.getText());
        buyAmount++;
        amountToBuy.setText(Integer.toString(buyAmount));
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        JFrame frame = new JFrame();
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        int buyAmount = Integer.parseInt(amountToBuy.getText());
        switch (buyAmount) {
            case 1:
                JOptionPane.showMessageDialog(frame, "Can not order less than one item");
                break;
            default:
                buyAmount--;
                amountToBuy.setText(Integer.toString(buyAmount));
                break;
        }
    }//GEN-LAST:event_minusButtonActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed

        currentCustomerFoodList.removeAllElements();
        int buyAmount = Integer.parseInt(amountToBuy.getText());

        for (int i = 0; i < buyAmount; i++) {
            if (customersSelection != null) {
                newCustomer.addToMyFoodList(customersSelection);
            }

        }
        for (int i = 0; i < newCustomer.getMyFoodList().size(); i++) {
            currentCustomerFoodList.addElement(newCustomer.getMyFoodList().get(i).getName());
            //System.out.println(newCustomer.getMyFoodList().get(i).toString());
        }
        orderListTotalPriceLabel.setText(Double.toString(newCustomer.getFoodPrice()));
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        registerPanel.setVisible(false);
        planePanel.setVisible(false);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(true);

        jTextArea2.setText("");
        jTextArea2.append("Name: " + newCustomer.getName() + "\n");
        jTextArea2.append("ID Number: " + newCustomer.getiD() + "\n");
        jTextArea2.append("Fight: " + customerPlane.getPlaneID() + "\n");
        jTextArea2.append("Seat number: " + ticket.getSeatType() + " " + ticket.getSeatNumber() + "\n");
        jTextArea2.append("Price: " + ticket.getPrice() + " SEK \n");
        jTextArea2.append("Reserved food : \n");
        newCustomer.getMyFoodList().forEach(s -> jTextArea2.append(s + "\n"));
        jTextArea2.append("Total food price: " + newCustomer.getFoodPrice() + " SEK \n");
        jTextArea2.append("-------------\n");
        jTextArea2.append("Total: " + (ticket.getTotalPrice() + newCustomer.getFoodPrice()) + " SEK \n");


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        registerPanel.setVisible(false);
        planePanel.setVisible(true);
        foodContainPanel.setVisible(false);
        reviewPanel.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        Flight flightTest;
        String selectFlight = JOptionPane.showInputDialog(this, "Type in the plane iD: ");
        int inputNumberTickets;
        for (Flight next : flightList) {
            if (next.getPlaneID().equalsIgnoreCase(selectFlight)) {
                flightTest = next;
                int ticketLeft = flightTest.getTotalNoAvailableSeat();
                String inputString = JOptionPane.showInputDialog(this, "input number of tickets you want to buy, maximum " + (ticketLeft - 1));
                if (inputString != null) {
                    inputNumberTickets = Integer.parseInt(inputString);
                    Customer customerTest = new Customer();
                    if (inputNumberTickets < ticketLeft) {
                        int i = inputNumberTickets;

                        for (Ticket nextTicket : flightTest.getTicketList().getList()) {
                            if (nextTicket.getCustomer() == null && i != 0) {
                                customerTest.setName("CustomerTest00" + i);
                                customerTest.setiD("12" + i + "234" + i);
                                nextTicket.setCustomer(customerTest);
                                i--;
                            }
                        }

                        jTextArea1.append(flightTest.getPlaneID() + ": " + inputNumberTickets + " tickets are sold\n");
                        jTextArea1.append(flightTest.getPlaneID() + ": " + flightTest.getTotalNoAvailableSeat() + " ticket left\n");
                    }
                }

            }

        }


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cancelButtonReviewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonReviewPanelActionPerformed
        startPanel.setVisible(true);
        bookPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonReviewPanelActionPerformed

    private void cancelButtonPlanePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPlanePanelActionPerformed
        startPanel.setVisible(true);
        bookPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonPlanePanelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     
        
        String selectedMenuItem = (String) currentMenuCombox.getSelectedItem();
        if (selectedMenuItem != null) {

            customersSelection = chosenMenu.findFoodByName(selectedMenuItem);
            jTextArea3.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getDescription());
            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(currentMenuCombox.getSelectedItem().toString()));
            menuItemPriceLabel.setText(chosenMenu.findFoodByName(currentMenuCombox.getSelectedItem().toString()).getPrice().toString());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void initCustomComponents() {
        //currentMenuCombox.removeAllElements();
        //Collections.sort(chosenMenu.getList());
        for (int i = 0; i < chosenMenu.getListSize(); i++) {

            currentMenuCombox.addElement(chosenMenu.getFoodAtIndex(i).getName());

        }
    }

    public int convertUserInputToInt(String userInput) {

        if (userInput == null || userInput.isEmpty()) {
            userInput = "1";
        }
        StringBuilder sb = new StringBuilder();
        boolean found = false;
        for (char c : userInput.toCharArray()) {
            if (Character.isDigit(c)) {
                sb.append(c);
                found = true;
            } else if (found) {
                // If we already found a digit before and this char is not a digit, stop looping
                break;
            }
        }
        userInput = sb.toString();
        if (sb.toString().isEmpty() || sb.toString() == null) {
            userInput = "1";
        }

        int buyAmount = Integer.parseInt(userInput);
        if (buyAmount <= 0) {
            buyAmount = 1;
        }
        return buyAmount;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        List<Flight> flightList = new ArrayList<>();

        Flight saab0001 = new Saab();
        saab0001.setPlaneID("SAAB0001");
        flightList.add(saab0001);
        Flight saab0002 = new Saab();
        saab0002.setPlaneID("SAAB0002");
        flightList.add(saab0002);
        Flight saab0003 = new Saab();
        saab0003.setPlaneID("SAAB0003");
        flightList.add(saab0003);

        Flight saab0004 = new Saab();
        saab0004.setPlaneID("SAAB0004");
        flightList.add(saab0004);

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BookingFrame bk = new BookingFrame(flightList);
                bk.setVisible(true);

                flightList.stream().map((next) -> new Thread(new FlightInformation(next, bk.jTextArea1))).forEachOrdered((flightinfo) -> {
                    flightinfo.start();
                });
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JLabel amountToBuy;
    private javax.swing.JPanel bookPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelButtonPlanePanel;
    private javax.swing.JButton cancelButtonRegisterPanel;
    private javax.swing.JButton cancelButtonReviewPanel;
    private javax.swing.JButton clearListButton;
    private javax.swing.JPanel containPanel;
    private javax.swing.JRadioButton economyClassButton;
    private javax.swing.JRadioButton firstClassButton;
    private javax.swing.JPanel foodContainPanel;
    private javax.swing.JPanel foodPanel1;
    private javax.swing.JLabel iDLabel;
    private javax.swing.JTextField iDTextField;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel menuAmountPanel;
    public javax.swing.JLabel menuItemPriceLabel;
    private javax.swing.JPanel menuItemPricePanel;
    private java.awt.Button minusButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    public javax.swing.JLabel orderListItemPriceLabel;
    public javax.swing.JLabel orderListTotalPriceLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JPanel planePanel;
    private java.awt.Button plusButton;
    private javax.swing.JButton previousButtonReviewPanel;
    private javax.swing.JPanel radioButtonPanel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton removeItemFromListButton;
    private javax.swing.JPanel reviewPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JPanel subPlanePanel;
    private javax.swing.JPanel subStartPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
